[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiarray = "0.1.3"
ndarray = "0.15.6"
petgraph = "0.6.4"
rand = "0.8.5"